"""ajout timeline

Revision ID: 148378701b4f
Revises: ac5de93bc76a
Create Date: 2025-06-08 12:23:57.981466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148378701b4f'
down_revision = 'ac5de93bc76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('scan_id', sa.String(length=255), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zap_scan_results', schema=None) as batch_op:
        batch_op.alter_column('scan_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zap_scan_results', schema=None) as batch_op:
        batch_op.alter_column('scan_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('timeline_events')
    # ### end Alembic commands ###
