"""Update SQLMapScanResult model

Revision ID: f870db34f559
Revises: 0c282c0bf930
Create Date: 2025-05-31 15:15:19.766602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f870db34f559'
down_revision = '0c282c0bf930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sql_map_scan_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_forms_crawl', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sql_map_scan_results', schema=None) as batch_op:
        batch_op.drop_column('enable_forms_crawl')

    # ### end Alembic commands ###
