"""Update SQLMapScanResult model

Revision ID: 0c282c0bf930
Revises: dc2961ee0d3a
Create Date: 2025-05-31 09:41:47.547734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c282c0bf930'
down_revision = 'dc2961ee0d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sql_map_scan_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dbms', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vulnerabilities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sql_map_scan_results', schema=None) as batch_op:
        batch_op.drop_column('vulnerabilities')
        batch_op.drop_column('dbms')

    # ### end Alembic commands ###
